// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACRdTFeS2z8BE1gwbiVzUWeZyVvMFPz1A',
    appId: '1:418960215776:web:b5026b8ad0f263e2298a85',
    messagingSenderId: '418960215776',
    projectId: 'chatty-38513',
    authDomain: 'chatty-38513.firebaseapp.com',
    storageBucket: 'chatty-38513.appspot.com',
    measurementId: 'G-EYE9X61T3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXVfJgXD55_g5IXXmsfgXUo-8ZjppLdt0',
    appId: '1:418960215776:android:c33c6163083391e4298a85',
    messagingSenderId: '418960215776',
    projectId: 'chatty-38513',
    storageBucket: 'chatty-38513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfggPIQswnHjlYSLR8LbDm1u3Bj-dWrZk',
    appId: '1:418960215776:ios:ba654dd3d50ebd4a298a85',
    messagingSenderId: '418960215776',
    projectId: 'chatty-38513',
    storageBucket: 'chatty-38513.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfggPIQswnHjlYSLR8LbDm1u3Bj-dWrZk',
    appId: '1:418960215776:ios:ba654dd3d50ebd4a298a85',
    messagingSenderId: '418960215776',
    projectId: 'chatty-38513',
    storageBucket: 'chatty-38513.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACRdTFeS2z8BE1gwbiVzUWeZyVvMFPz1A',
    appId: '1:418960215776:web:bc0386e20cfa24c3298a85',
    messagingSenderId: '418960215776',
    projectId: 'chatty-38513',
    authDomain: 'chatty-38513.firebaseapp.com',
    storageBucket: 'chatty-38513.appspot.com',
    measurementId: 'G-084412L53S',
  );
}
